AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'lib/tasks/*.rake'
    - 'bin/*'
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 100
